title: units-of-measure
lib: <em>units-of-measure</em>

email: units@kunalsheth.info
description: >- # this means to ignore newlines until "baseurl:"
  Type-safe dimensional analysis and unit conversion in Kotlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://units.kunalsheth.info" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  kunalsheth

header_pages:
  - about.md

markdown: kramdown
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
